### ISSUE TITLE
Code from Julia statistics tutorial gives errors in recent versions

### ISSUE THREAD

**Issue by johannes-riecken** [JuliaLang/julia-tutorial#2]
I just tried out Julia 0.4.1 and followed the stats presentation. I ran the Pkg.add("...") command for "DataFrames" (v0.6.10), "Distributions" (v0.8.7), "GLM" (v0.4.8) and "RDatasets" (v0.1.2). 
Running the presentation's code gives multiple errors. For example I noticed I had to write "RDatasets" instead of "RDataSets" and form=dataset("datasets","Formaldehyde") instead of form=data(...). 
The regression command fm=lm(:(optden ~ carb),form) fails with
ERROR: MethodError: `fit` has no method matching fit(::Type{GLM.LinearModel{T<:G
LM.LinPred}}, ::Expr, ::DataFrames.DataFrame)
There is probably more code in the presentation that doesn't work any more; I only got this far.

**Comment by ViralBShah** [comment]
I suspect this needs to be filed against GLM.jl.

**Comment by nalimilan** [comment]
What "stats presentation" do you refer to?

Regarding the second error, it should now be `fm = lm(optden ~ carb, form)`.

**Comment by nalimilan** [comment]
Ah, sorry, I hadn't noticed the issue was filed against the julia-tutorial repo. So the files are indeed out of date. @ViralBShah Are these tutorials supposed to be updated, or should we simply add a big warning? It would be more convenient to offer this content as a webpage, if we need to update them.

**Comment by ViralBShah** [comment]
Now that we know - we should at least add a warning there. But yes, this will be tough. The long term solution is to have a standard set of tutorials on the JuliaStats website, which are part of the JuliaStats documentation.

**Comment by ViralBShah** [comment]
cc: @simonbyrne

**Comment by tkelman** [comment]
This is way outdated, I'm moving the repo to JuliaArchive.

**Comment by ViralBShah** [comment]
Wow, a blast from the past!
